web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using web.Models;
using web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace web.Controllers
{
    public class HomeController : Controller
    {
        private readonly EhomeContext _context;
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<ApplicationUser> _usermanager;


        public HomeController(ILogger<HomeController> logger, EhomeContext context, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            _context = context;
            _usermanager = userManager;
        }
        public async Task<IActionResult> IndexAsync(string group, int? listing, int? region, int? size, int? year, int? price)
        {
            var currentUser = await _usermanager.GetUserAsync(User);
            ViewData["isLogged"] = currentUser != null ? currentUser.Id : null;
            ViewData["Favorite"] = currentUser != null ? _context.Favorite.Where(l => l.User == currentUser).ToList() : null;
            
            if(this.NoneNull(group, listing, region, size, year, price)) {
                var (lSize, hSize) = this.Deconstruct(size, "size");
                var (lYear, hYear) = this.Deconstruct(year, "year");
                var (lPrice, hPrice) = this.Deconstruct(price, "price");

                var ehomeContext = _context.Listings
                    .Include(l => l.LType)
                    .Include(l => l.REGroup)
                    .Include(l => l.Region)
                    .Where(l => l.REGroup.Group == group && l.ListingType == listing && l.RegionId == region
                        && (lSize <= l.Size && l.Size <= hSize)
                        && (lYear <= l.Year && l.Year <= hYear)
                        && (lPrice <= l.Price && l.Price <= hPrice))
                    .OrderByDescending(l => l.DateOfEntry);

                ViewData["ResultName"] = "Najdene Nepremičnine";
                ViewData["Group"] = new SelectList(_context.RealEstateGroup.Select(e => new {e.Group}).Distinct(), "Group", "Group", group);
                ViewData["ListingType"] = new SelectList(_context.ListingType, "Id", "Type", listing);
                ViewData["Region"] = new SelectList(_context.Region, "Id", "Name", region);
                ViewData["Size"] = new SelectList(_context.SizeOptions, "Id", "DisplayName", size);
                ViewData["Year"] = new SelectList(_context.YearOptions, "Id", "DisplayName", year);
                ViewData["Price"] = new SelectList(_context.PriceOptions.Where(e => e.ListingType == listing), "Id", "DisplayName", price);

                return View(await ehomeContext.ToListAsync());
            }
            else {
                var ehomeContext = _context.Listings
                    .Include(l => l.LType)
                    .Include(l => l.REGroup)
                    .Include(l => l.Region)
                    .OrderByDescending(l => l.DateOfEntry);

                ViewData["ResultName"] = "Nazadnje Dodane";

                ViewData["Group"] = new SelectList(_context.RealEstateGroup.Select(e => new {e.Group}).Distinct(), "Group", "Group","Stanovanje");
                ViewData["ListingType"] = new SelectList(_context.ListingType, "Id", "Type",2);
                ViewData["Region"] = new SelectList(_context.Region, "Id", "Name",8);
                ViewData["Size"] = new SelectList(_context.SizeOptions, "Id", "DisplayName");
                ViewData["Year"] = new SelectList(_context.YearOptions, "Id", "DisplayName",9);
                ViewData["Price"] = new SelectList(_context.PriceOptions.Where(e => e.ListingType == 2), "Id", "DisplayName",9);

                return View(await ehomeContext.ToListAsync());
            }

            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("ListingId")] Favorite favorite)
        {
            var currentUser = await _usermanager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                favorite.User = currentUser;
                _context.Add(favorite);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var favorite = await _context.Favorite.FindAsync(id);
            _context.Favorite.Remove(favorite);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private (int lo, int hi) Deconstruct(int? id, string t) {
            string o = null;
            switch(t) {
                case "size":
                    o = _context.SizeOptions.Where(e => e.Id == id).First().CodeName; break;
                case "year":
                    o = _context.YearOptions.Where(e => e.Id == id).First().CodeName; break;
                case "price":
                    o = _context.PriceOptions.Where(e => e.Id == id).First().CodeName; break;
            }
            string[] p = o.Split('-');
            return (Int32.Parse(p[0]), Int32.Parse(p[1]));
        }

        private bool NoneNull(string group, int? listing, int? region, int? size, int? year, int? price)
            => group != null && listing != null && region != null && size != null && year != null && price != null;
    }
}

web/Controllers/ListingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web.Data;
using web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace web.Controllers
{
    public class ListingsController : Controller
    {
        private readonly EhomeContext _context;
        private readonly UserManager<ApplicationUser> _usermanager;

        public ListingsController(EhomeContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _usermanager = userManager;
        }

        // GET: Listings
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var currentUser = await _usermanager.GetUserAsync(User);
            var ehomeContext = _context.Listings
                .Include(l => l.Region)
                .Include(l => l.LType)
                .Include(l => l.REGroup)
                .Include(l => l.REGroup.REType)
                .Where(l => l.Owner == currentUser);
                
            return View(await ehomeContext.ToListAsync());
        }

        // GET: Listings/Details/5
        [HttpGet]
        [Route("Listings/Details/{id?}")]
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var listing = await _context.Listings
                .Include(l => l.Region)
                .Include(l => l.LType)
                .Include(l => l.REGroup)
                .Include(l => l.REGroup.REType)
                .Include(l => l.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (listing == null)
            {
                return NotFound();
            }

            var userid = listing.Owner.Id;

            var user = await _usermanager.GetUserAsync(User);
            if(user != null && await _usermanager.IsInRoleAsync(user, "Administrator"))
                ViewData["UserId"] = userid;

            return View(listing);
        }

        // GET: Listings/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["ListingType"] = new SelectList(_context.ListingType, "Id", "Type");
            ViewData["GroupId"] = new SelectList(_context.RealEstateGroup, "Id", "FullName");
            ViewData["RegionId"] = new SelectList(_context.Region, "Id", "Name");
            return View();
        }

        // POST: Listings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("RegionId,Address,Size,Year,ImageLink,Description,Price,GroupId,ListingType")] Listing listing)
        {
            var currentUser = await _usermanager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                if(listing.ImageLink == "" || listing.ImageLink == null)
                    listing.ImageLink = this.getRandomImage();
                listing.DateOfEntry = DateTime.Now;
                listing.Owner = currentUser;
                listing.OwnerId = currentUser.Id;
                _context.Add(listing);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ListingType"] = new SelectList(_context.ListingType, "Id", "Type", listing.ListingType);
            ViewData["GroupId"] = new SelectList(_context.RealEstateGroup, "Id", "FullName", listing.GroupId);
            ViewData["RegionId"] = new SelectList(_context.Region, "Id", "Name", listing.RegionId);
            return View(listing);
        }

        // GET: Listings/Edit/5/{userid?}
        [Authorize]
        [HttpGet]
        [Route("Listings/Edit/{id?}")]
        public async Task<IActionResult> Edit(int? id)
        {
            var currentUser = await _usermanager.GetUserAsync(User);
            ViewData["isLogged"] = currentUser != null;
            if (id == null)
            {
                return NotFound();
            }

            var listing = await _context.Listings.Include(l => l.Owner).FirstOrDefaultAsync(m => m.Id == id);
            var group = await _context.RealEstateGroup.FindAsync(listing.GroupId);
            if (listing == null)
            {
                return NotFound();
            }
            ViewData["ListingType"] = new SelectList(_context.ListingType, "Id", "Type", listing.ListingType);
            ViewData["FullGroup"] = new SelectList(_context.RealEstateGroup.Where(e => e.Group == group.Group), "Id", "FullName", group.TypeId);
            ViewData["Region"] = new SelectList(_context.Region, "Id", "Name", listing.RegionId);
            var user = await _usermanager.GetUserAsync(User);
            if(user != null && await _usermanager.IsInRoleAsync(user, "Administrator"))
                ViewData["UserId"] = listing.Owner.Id;
            return View(listing);
        }

        // POST: Listings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("Listings/Edit/{id?}")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DateOfEntry,RegionId,Address,Size,Year,ImageLink,Description,Price,GroupId,ListingType")] Listing listing)
        {
            if (id != listing.Id)
            {
                return NotFound();
            }
            var l = await _context.Listings.Include(l => l.Owner).FirstOrDefaultAsync(m => m.Id == id);
            var group = await _context.RealEstateGroup.FindAsync(l.GroupId);
            ViewData["ListingType"] = new SelectList(_context.ListingType, "Id", "Type", l.ListingType);
            ViewData["FullGroup"] = new SelectList(_context.RealEstateGroup.Where(e => e.Group == group.Group), "Id", "FullName", group.TypeId);
            ViewData["Region"] = new SelectList(_context.Region, "Id", "Name", l.RegionId);

            if (ModelState.IsValid)
            {
                try
                {
                    if(listing.ImageLink == "" || listing.ImageLink == null)
                        listing.ImageLink = this.getRandomImage();
                    _context.DetachLocal(listing, id);
                    _context.Update(listing);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ListingExists(listing.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                var user = await _usermanager.GetUserAsync(User);
                if(user != null && await _usermanager.IsInRoleAsync(user, "Administrator"))
                    return RedirectToAction("Details", "Admin", new {id=l.Owner.Id});

                return RedirectToAction(nameof(Index));
            }
            return View(listing);
        }

        // GET: Listings/Delete/5
        [HttpGet]
        [Route("Listings/Delete/{id?}")]
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var listing = await _context.Listings
                .Include(l => l.LType)
                .Include(l => l.REGroup)
                .Include(l => l.Region)
                .Include(l => l.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (listing == null)
            {
                return NotFound();
            }

            var user = await _usermanager.GetUserAsync(User);
            if(user != null && await _usermanager.IsInRoleAsync(user, "Administrator"))
                ViewData["UserId"] = listing.Owner.Id;
            return View(listing);
        }

        // POST: Listings/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [Route("Listings/Delete/{id}")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var listing = await _context.Listings.Include(l => l.Owner).FirstOrDefaultAsync(m => m.Id == id);
            _context.Listings.Remove(listing);
            await _context.SaveChangesAsync();
            
            var user = await _usermanager.GetUserAsync(User);
            if(user != null && await _usermanager.IsInRoleAsync(user, "Administrator"))
                return RedirectToAction("Details", "Admin", new {id=listing.Owner.Id});
            return RedirectToAction(nameof(Index));
        }

        private bool ListingExists(int id)
        {
            return _context.Listings.Any(e => e.Id == id);
        }

        private string getRandomImage(){
            var rand = new Random();
            var i = rand.Next(1, 6);
            switch(i)
            {
                case 1: return "https://miro.medium.com/max/10816/1*eO3CIaFBe7LMRePApDwSYA.jpeg";
                case 2: return "https://cache.100kvadratov.si/image/project/58/large_ljn/1/accamera1__5d2f222a8d257.jpg";
                case 3: return "https://img.nepremicnine.link/slonep_oglasi2/7520688.jpg";
                case 4: return "https://www.kras-nepremicnine.si/site/assets/files/1393/image1.jpeg";
                case 5: return "https://cache.100kvadratov.si/image/item/83/site/list_portal/4/img-4bd56aaebaf4bcfca80a2b79b368f5dc-v__5ebbde75109ae.jpg";

web/Views/Home/Index.cshtml
@model IEnumerable<web.Models.Listing>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    @* Search filter *@
    <partial name="_FilterPartial" />


      @if(Model.Count() != 0) {
    <h2 style="margin-top: 50px !important;">@ViewBag.ResultName</h2>

    <div class="recentlyAddedMain">
      
        @foreach (var item in Model)
        {
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="@Html.DisplayFor(modelItem => item.ImageLink)">
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.REGroup.Group) @Html.DisplayFor(modelItem =>
                                                                                                item.LType.Type)</h5>
                    <p class="card-text"><span>Velikost:</span> @Html.DisplayFor(modelItem =>
                                                                   item.Size) &#x33A1</p>
                    <p class="card-text"><span>Naslov:</span> @Html.DisplayFor(modelItem => item.Address)</p>
                    <p class="card-text"><span>Cena:</span> @Html.DisplayFor(modelItem => item.Price)</p>

                <div style="display: flex; justify-content: space-between; align-items: center;">
                    <a class="btn btn-primary" asp-route-id="@item.Id" asp-controller="Listings" asp-action="Details">Odpri
                        oglas</a>

                    @if (@ViewBag.isLogged != null)
                    {
                       
                            @if (item.isFavoriteForUser(@ViewBag.isLogged))
                            {
                                <form id="form_unfavorite_@item.Id" asp-action="Delete">
                                    <input type="hidden" name="id" value="@item.getFavoriteId(@ViewBag.isLogged)" />
                                    <a href="javascript:{}" ,
                                        onclick="document.getElementById('form_unfavorite_@item.Id').submit();"
                                        onsubmit="return false">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart-fill" fill="red"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd"
                                                d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
                                        </svg>
                                    </a>
                                </form>
                            }
                            else {
                                <form id="form_favorite_@item.Id" asp-action="Create">
                                    <input type="hidden" name="ListingId" value="@item.Id" />
                                    <a href="javascript:{}" , onclick="document.getElementById('form_favorite_@item.Id').submit();"
                                        onsubmit="return false">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart" fill="black"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd"
                                                d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                                        </svg>
                                    </a>
                                </form>
                            }
                            
                    }
                </div>

                </div>
            </div>
        }
    
    </div>
      }
      else {
        <h2 style="margin-top: 100px;">Ni Najdenih Nepremičnin :(</h2>

      }
</div>

web/Views/Home/_FilterPartial.cshtml
<form id="filter_form" method="get">
    <h2 style=" margin-bottom:50px ">Iskanje Nepremičnin</h2>
    <div class="search-filter">
        <div style="display: flex; width: 100%; justify-content: space-between; padding:10px">
            <div class="filter-row">
                <label class="mr-sm-2" for="group">VRSTA NEPREMIČNINE</label>
                <select class="custom-select mr-sm-2" id="group" name="group" asp-items="ViewBag.Group">
                </select>
            </div>
            <div class="filter-row">
                <label class="mr-sm-2" for="listing">VRSTA PONUDBE</label>
                <select class="custom-select mr-sm-2" id="listing" name="listing" asp-items="ViewBag.ListingType"
                    onchange="document.getElementById('filter_form').submit();">
                </select>
            </div>
        </div>
        <div style="display: flex; width: 100%; justify-content: space-between; padding:10px">
            <div class="filter-row">
                <label class="mr-sm-2" for="region">REGIJA</label>
                <select class="custom-select mr-sm-2" id="region" name="region" asp-items="ViewBag.Region">
                </select>
            </div>
            <div class="filter-row">
                <label class="mr-sm-2" for="size">VELIKOST (&#x33A1)</label>
                <select class="custom-select mr-sm-2" id="size" name="size" asp-items="ViewBag.Size">
                </select>
            </div>
        </div>
        <div style="display: flex; width: 100%; justify-content: space-between; padding:10px">
            <div class="filter-row">
                <label class="mr-sm-2" for="year">LETO</label>
                <select class="custom-select mr-sm-2" id="year" name="year" asp-items="ViewBag.Year">
                </select>
            </div>
            <div class="filter-row">
                <label class="mr-sm-2" for="price">CENA (&euro;)</label>
                <select class="custom-select mr-sm-2" id="price" name="price" asp-items="ViewBag.Price">
                </select>
            </div>

        </div>
        <div style="width: 70%; padding: 10px;">
            @* <button type="button" class="btn btn-primary" asp-route-id="2" asp-controller="Home"
                asp-action="Index">IŠČI
                NEPREMIČNINE</button> *@
            <input type="submit" value="IŠČI NEPREMIČNINE" asp-controller="Home" asp-action="Index"
                class="btn btn-primary">
        </div>

    </div>
</form>